version: '3.1'


services:
  #
  # Clickhouse
  #
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./conf.d/config.xml:/etc/clickhouse-server/config.d/kafka.xml
    environment:
      - CLICKHOUSE_DB=house
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    ulimits:
      nofile: 262144
    profiles: ["cluster"]

  #
  # EventSim
  #
  eventsim:
    image: eventsim:latest
    build:
      context: .
      dockerfile: eventsim.Dockerfile
    command: -c "examples/example-config.json" --start-time "2022-01-01T00:00:00" --end-time "2023-01-01T00:00:00" --nusers 10 --kafkaBrokerList kafka:29092
    profiles: ["eventsim"]

  #
  # Apache Kafka
  #
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: bitnami/zookeeper:3.6.4
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    profiles: ["cluster"]

  kafka:
    hostname: kafka
    container_name: kafka 
    image: bitnami/kafka:3.1.2
    ports:
      - 9092:9092
      - 9101:9101
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
    depends_on:
      - zookeeper
    profiles: ["cluster"]

  init-kafka:
    image: bitnami/kafka:3.1.2
    depends_on:
      - kafka 
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      kafka-topics --bootstrap-server kafka:29092 --list
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic listen_events --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:29092 --list
      "
    profiles: ["cluster"]
